rust: add RUST_BACKTRACE=1 setting
Get better backtraces, like:

    vm hyperfine (avar/support-build-command $>) 101 $ RUST_BACKTRACE=1 cargo build
       Compiling hyperfine v1.12.0 (/home/avar/g/hyperfine)
    error: failed to run custom build command for `hyperfine v1.12.0 (/home/avar/g/hyperfine)`

    Caused by:
      process didn't exit successfully: `/home/avar/g/hyperfine/target/debug/build/hyperfine-4b69b1b9aaaa8486/build-script-build` (exit code: 101)
      --- stderr
      thread 'main' panicked at 'Argument short must be unique

            -s is already in use', /home/avar/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/parser.rs:193:13
      stack backtrace:
         0: rust_begin_unwind
                   at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:483
         1: std::panicking::begin_panic_fmt
                   at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:437
         2: clap::app::parser::Parser::debug_asserts
                   at /home/avar/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/parser.rs:193
         3: clap::app::parser::Parser::add_arg
                   at /home/avar/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/parser.rs:302
         4: clap::app::App::arg
                   at /home/avar/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/mod.rs:794
         5: build_script_build::build_app
                   at ./src/app.rs:23
         6: build_script_build::main
                   at ./build.rs:15
         7: core::ops::function::FnOnce::call_once
                   at /usr/src/rustc-1.48.0/library/core/src/ops/function.rs:227
      note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Not:

    vm hyperfine (avar/support-build-command $>) 101 $ RUST_BACKTRACE=0 cargo build
       Compiling hyperfine v1.12.0 (/home/avar/g/hyperfine)
    error: failed to run custom build command for `hyperfine v1.12.0 (/home/avar/g/hyperfine)`

    Caused by:
      process didn't exit successfully: `/home/avar/g/hyperfine/target/debug/build/hyperfine-4b69b1b9aaaa8486/build-script-build` (exit code: 101)
      --- stderr
      thread 'main' panicked at 'Argument short must be unique

            -s is already in use', /home/avar/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/parser.rs:193:13
      note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    vm hyperfine (avar/support-build-command $>) 101 $