offlineimap: Implement IDLE support, in theory
This crashed after 20 minutes, and I haven't had a crash before:

    Folder INBOX [acc: Work]:
     ERROR: ERROR in syncfolder for Work folder INBOX: Traceback (most recent call last):
      File "/home/avar/g/offlineimap/offlineimap/accounts.py", line 536, in syncfolder
        statusfolder.cachemessagelist()
      File "/home/avar/g/offlineimap/offlineimap/folder/LocalStatusSQLite.py", line 235, in cachemessagelist
        flags = set(row[1])
    TypeError: 'NoneType' object is not iterable

I don't really need this, it doesn't speed things up for me that much
and seems to eat just as much if not more CPU (due to the N number of
threads), so I'm just going back to my dumb while loop.