.gitconfig: don't verify ssl traffic due to github fail
    mc01eventcron-01 ~ (master=) $ export http_proxy=http://webproxy.lhr1.activehotels.net:3128
    mc01eventcron-01 ~ (master=) $ export https_proxy=http://webproxy.lhr1.activehotels.net:3128
    mc01eventcron-01 ~ (master=) $ git pull
    error: SSL certificate problem, verify that the CA cert is OK. Details:
    error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed while accessing https://github.com/avar/dotfiles.git/info/refs

    fatal: HTTP request failed

I have no idea if the root cause of this is related to our systems or
to github.